[project]
name = "soundnovel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "chardet>=5.2.0",
    "flask>=3.1.1",
    "openai>=1.99.1",
    "psutil>=7.0.0",
    "tqdm>=4.67.1",
    "werkzeug>=3.1.3",
]
